### PR TITLE
Converted unified add layers to use new API.

### PR DESCRIPTION
**Pull request by theduckylittle**
## What does this PR do?

No longer searching both the Registry instance
  and GeoNode. It will now only search using the
  /api/base/search endpoint.

### Screenshot
No changes in visual presentation.

### Related Issue

NODE-759, NODE-760, NODE-763

### CODE REVIEW

**Comment by davisc** [comment]
@theduckylittle Is category filtering supported?

**Comment by theduckylittle** [comment]
This is *passing* category__in to the search API *and* I do not get any responses from registry when I search using category.  I am not sure if registry layers are correctly being given categories but that would be a bug in the API and not MapLoom.

**Comment by theduckylittle** [comment]
This is the relevant line of code: https://github.com/boundlessgeo/MapLoom/pull/69/files#diff-bf51fd952b13e52184d58caa03a08502R475

**Comment by theduckylittle** [comment]
Just tested against the latest version of the API with geogig fixes and all is well.

**Comment by theduckylittle** [comment]
NODE-719 is also affected.

**Pull request merged**
